const permissions = {
  ViewPermissions: 'view-permissions',
  ViewAllRoles: 'view-roles',
  CreateRole: 'create-role',
  ViewRole: 'view-role',
  UpdateRole: 'update-role',
  DeleteRole: 'delete-role',
  ViewAllUsers: 'view-users',

  CreateUser: 'create-user',
  ViewUser: 'view-user',
  UpdateUser: 'update-user',
  DeleteUser: 'delete-user',

  ViewAllWorkflows: 'view-workflows',
  CreateWorkflow: 'create-workflow',
  ViewWorkflow: 'view-workflow',
  UpdateWorkflow: 'update-workflow',
  DeleteWorkflow: 'delete-workflow',
  ViewAllForms: 'view-forms',
  CreateForm: 'create-form',
  ViewForm: 'view-form',
  UpdateForm: 'update-form',
  DeleteForm: 'delete-form',
  ViewTriggers: 'view-triggers',
  ViewActions: 'view-actions',
  ViewReturnUsers: 'view-return-users',
  ViewLdapUsers: 'view-ldap-users',
  ViewLdapBranches: 'view-ldap-branches',
  ViewLdapProvinces: 'view-ldap-provinces',
  ViewAllDepartments: 'view-departments',
  CreateDepartment: 'create-department',
  ViewDepartment: 'view-department',
  UpdateDepartment: 'update-department',
  DeleteDepartment: 'delete-department',

  ViewAllCategories: 'view-categories',
  CreateCategory: 'create-category',
  ViewCategory: 'view-category',
  UpdateCategory: 'update-category',
  DeleteCategory: 'delete-category',

  ViewAllPrintTemplate: 'view-print-templates',
  CreatePrintTemplate: 'create-print-template',
  ViewPrintTemplate: 'view-print-template',
  UpdatePrintTemplate: 'update-print-template',
  DeletePrintTemplate: 'delete-print-template',

  ViewAllRequests: 'view-all-requests',
  ViewRequests: 'view-requests',
  ViewRequest: 'view-request',
  PerformAllRequestAction: 'perform-all-request-action',
  PerformRequestAction: 'perform-request-action',

  ViewAllInternalRequests: 'view-internal-all-requests',
  ViewInternalRequests: 'view-internal-requests',
  ViewInternalRequest: 'view-internal-request',
  PerformAllInternalRequestAction: 'perform-all-internal-request-action',
  PerformInternalRequestAction: 'perform-internal-request-action',

  ViewAllGroups: 'view-groups',
  ViewGroup: 'view-group',
  CreateGroup: 'create-group',
  UpdateGroup: 'update-group',
  DeleteGroup: 'delete-group',

  ViewAllBranches: 'view-branches',
  ViewBranch: 'view-branch',
  CreateBranch: 'create-branch',
  UpdateBranch: 'update-branch',
  Deletebranch: 'delete-branch',

  ViewAllGroupUser: 'view-all-group-user',
  AddGroupUser: 'add-group-user',
  DeleteGroupUser: 'delete-group-user',
  ViewAllLogs: 'view-logs',
  ViewLog: 'view-log',
  CreateLog: 'create-log',
  UpdateLog: 'update-log',
  Delete_log: 'delete-log',
  ViewAllOpenWorkflow: 'view-open-workflows',
  ViewOpenWorkflow: 'view-open-workflow',
  CreateOpenWorkflow: 'create-open-workflow',
  UpdateOpenWorkflow: 'update-open-workflow',
  DeleteOpenWorkflow: 'delete-open-workflow',
  ViewBgSubForm: 'view-sub-form-bg',
  ViewLcSubForm: 'view-sub-form-lc',
  ViewPreView: 'view-preview',
  ViewSelfBranchRequest: 'view-self-branch-requests',
  LocalLC: 'local-lc',
  SwiftClose: 'swift-close',
  SendMail: 'send-mail',
  ViewReport: 'view-reports',

  CanViewBibiniRequests: 'view-bibini-requests',
  CanFillBibiniRequest: 'create-bibini-requests',

  CanAccessLC: 'access-form-LC',
  CanAccessBG: 'access-form-BG'
};

module.exports = permissions;
