const NONE = 0;
const VIEW = 1;
const VIEW_EDIT = 2;
const VIEW_EDIT_DELETE = 3;
const CURRENT_USER_ID = '1';
const TOKEN = 'x';
const CLIENT_TOKEN = 'y';
const ADMIN_USER = 'a';
const CLIENT_USER = 'b';
const CLIENT_USER_ID = 'c';
// SHOULD NOT BE CHANGES - API DEPENDANT
const SEND_EMAIL_HOURLY_ACCESS = 'HOURLY_ACCESS';
const EMAIL_OTP = 'EMAIL_OTP';
const PHONE_OTP = 'PHONE_OTP';

export {
  NONE,
  VIEW,
  VIEW_EDIT,
  VIEW_EDIT_DELETE,
  CURRENT_USER_ID,
  TOKEN,
  SEND_EMAIL_HOURLY_ACCESS,
  EMAIL_OTP,
  PHONE_OTP,
  ADMIN_USER,
  CLIENT_USER,
  CLIENT_TOKEN,
  CLIENT_USER_ID
};
